### ISSUE TITLE
why not add leading zero bytes to make childkey 32 bytes long?

### ISSUE THREAD

**Issue by bibibong** [btcsuite/btcutil#172]
See [extendedkey.go:297](https://github.com/btcsuite/btcutil/blob/b2bf7f89d674a3702182b7e15f52807896051af3/hdkeychain/extendedkey.go#L297)
The bytes length may be smaller than 32. Is there  any bug when deriving hardened private key?
The derived key with padding differs.

**Comment by onyb** [comment]
We only ever need to pad the private key bytes when further deriving a child extended key. This is already taken care of here:
https://github.com/btcsuite/btcutil/blob/4649e4b73b34090724fff8a302751260c20551fd/hdkeychain/extendedkey.go#L250-L258

The other thing we care about is whether the integer corresponding to the private child key bytes is valid for the secp256k1 elliptic curve. Here it doesn't matter if the serialization was done in 32 bytes or less, as long as the underlying crypto library can convert it to a [**`big.Int`**](https://golang.org/pkg/math/big/#Int) number.

Note that the `hdkeychain` package is tested against the official BIP-0032 test vectors, so I would be very surprised if there is a bug of the nature you describe.

Let me know if this answers your question. Otherwise, if you can provide a failing test case, I'll gladly take a look.

**Comment by silencer-Tsai** [comment]
From my point of view, this implementatin might get a wrong result in some case. As the [BIP32](https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki#private-parent-key--private-child-key) said, in the case of computing a child extended hardened private key from the parent private key, I = HMAC-SHA512(Key = cpar, Data = 0x00 || ser256(kpar) || ser32(i)). 
As for implementation, see [extendedkey.go](https://github.com/btcsuite/btcutil/blob/4649e4b73b34090724fff8a302751260c20551fd/hdkeychain/extendedkey.go#L250-L272).
If the length of *k.key* is less than 32, for example 31, then the Data = 0x00 || 31 bytes || 0x00 || ser32(i). *ser256(kpar)* just performs like another key leading with this 31 bytes and followed one 0x00. This is not consistent with the regulations of BIP32.

Here is a test vector. 

Seed(Hex): 1cae71ac5ed584ff88a078a119512d12bb61e5398521785e123b6d08809d44b2
* Chain m
  * ext pub: xpub661MyMwAqRbcEmwzw5S7mHW26Urp4kngnBFwoZUXSgakbHGs5bgZ7RYsqX9nyCP3YKqrJ2gVfaJc6waZBJC2VFsnmJB7iPSNA5LvmZpcBcQ
  * ext priv: xprv9s21ZrQH143K2HsXq3u7Q9ZHYT2KfJ4qQxLM1B4utM3miUwiY4NJZdEPzDpzbH7xxtMr3QfT2VH13rabABKkw1eLU83YC1QMeXsX3DBe2yP
* Chain m/44'
  * ext pub: xpub695cM7RLktQbMS9DgS2SmkGF6W4msU7dW3ZkshyPV5PVWsWyoNxtvSBtm6VPSbcBR3a1NSp9BYy3v3QhUTi8T1HDa6rMShYmF682N6BaYpk
  * ext priv: xprv9v6FwbtSvWrJ8x4kaQVSQcKWYUEHU1Pn8peA5KZmvjrWe5BqFqeeNdsQuqDXN9JqeAxmAvs5v682JLDQZJsB8Up4guNVPSGidN19N2iH1Lr
* Chain m/44'/0'
  * ext pub: xpub6Begh3MMx7oX3A7A1m6cCu2tXgqTPVQgoxQKx7TCsUreVbSqhxbTPt42whTwYgSmnSuVkMzLeBa734foBe6QvzcsoddEVyad9N5iW4ZBqSh
  * ext priv: xprv9xfLHXpU7kFDpg2gujZbqm69yezxz2gqSjUj9j3bK9Kfco7hARHCr5jZ6RAWF6E6drNhziP3UJ3iWGaEc7whBuqkzgzytsdkePT6b6iWKki

In Chain m/44'/0', this implementaion gets a wrong result. This is because the length of the serialization of its parant private key is 31 and we are deriving a hardened child private key. I tried to fix this bug with leading 0x00 and got another result. 

Seed(Hex): 1cae71ac5ed584ff88a078a119512d12bb61e5398521785e123b6d08809d44b2
* Chain m/44'/0'
  * ext pub: xpub6Begh3MMx7oX2KoJb5D9sfJruuqsqsrqBZTBBznYMRfk7RBo8EcKDodYJm529ykTr2wrK1KBKXCbdSPu74pA37hZmPxkCP3hbEJBuqJgruy
  * ext priv: xprv9xfLHXpU7kFDoqiqV3g9WXN8Mt1PSR8ypLXaPcNvo68mEcreahJ4g1K4TWqn4qu6HCKByGeivW9neAEzSS7idYdpGaGXJgvb79fxvV4qhse

I got the same result on [bip32.org](http://bip32.org/).

![image](https://user-images.githubusercontent.com/39208031/89793100-07a3c600-db58-11ea-8afa-bb61ee4f27c6.png)

As the result shows, this implementation might calculate a child key different from the one specified in BIP32 in some scenarios. As for the official BIP-0032 test vectors, the length of the serialization of their private key are all 32.

**Comment by silencer-Tsai** [comment]
From my point of view, this implementatin might get a wrong result in some case. As the [BIP32](https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki#private-parent-key--private-child-key) said, in the case of computing a child extended hardened private key from the parent private key, I = HMAC-SHA512(Key = cpar, Data = 0x00 || ser256(kpar) || ser32(i)). 
As for implementation, see [extendedkey.go](https://github.com/btcsuite/btcutil/blob/4649e4b73b34090724fff8a302751260c20551fd/hdkeychain/extendedkey.go#L250-#L272).
https://github.com/btcsuite/btcutil/blob/4649e4b73b34090724fff8a302751260c20551fd/hdkeychain/extendedkey.go#L250-L272
If the length of *k.key* is less than 32, for example 31, then the Data = 0x00 || 31 bytes || 0x00 || ser32(i). *ser256(kpar)* just performs like another key leading with this 31 bytes and followed one 0x00. This is not consistent with the regulations of BIP32.

Here is a test vector. 

Seed(Hex): 1cae71ac5ed584ff88a078a119512d12bb61e5398521785e123b6d08809d44b2
* Chain m
  * ext pub: xpub661MyMwAqRbcEmwzw5S7mHW26Urp4kngnBFwoZUXSgakbHGs5bgZ7RYsqX9nyCP3YKqrJ2gVfaJc6waZBJC2VFsnmJB7iPSNA5LvmZpcBcQ
  * ext priv: xprv9s21ZrQH143K2HsXq3u7Q9ZHYT2KfJ4qQxLM1B4utM3miUwiY4NJZdEPzDpzbH7xxtMr3QfT2VH13rabABKkw1eLU83YC1QMeXsX3DBe2yP
* Chain m/44'
  * ext pub: xpub695cM7RLktQbMS9DgS2SmkGF6W4msU7dW3ZkshyPV5PVWsWyoNxtvSBtm6VPSbcBR3a1NSp9BYy3v3QhUTi8T1HDa6rMShYmF682N6BaYpk
  * ext priv: xprv9v6FwbtSvWrJ8x4kaQVSQcKWYUEHU1Pn8peA5KZmvjrWe5BqFqeeNdsQuqDXN9JqeAxmAvs5v682JLDQZJsB8Up4guNVPSGidN19N2iH1Lr
* Chain m/44'/0'
  * ext pub: xpub6Begh3MMx7oX3A7A1m6cCu2tXgqTPVQgoxQKx7TCsUreVbSqhxbTPt42whTwYgSmnSuVkMzLeBa734foBe6QvzcsoddEVyad9N5iW4ZBqSh
  * ext priv: xprv9xfLHXpU7kFDpg2gujZbqm69yezxz2gqSjUj9j3bK9Kfco7hARHCr5jZ6RAWF6E6drNhziP3UJ3iWGaEc7whBuqkzgzytsdkePT6b6iWKki

In Chain m/44'/0', this implementaion gets a wrong result. This is because the length of the serialization of its parant private key is 31 and we are deriving a hardened child private key. I tried to fix this bug with leading 0x00 and got another result. 

Seed(Hex): 1cae71ac5ed584ff88a078a119512d12bb61e5398521785e123b6d08809d44b2
* Chain m/44'/0'
  * ext pub: xpub6Begh3MMx7oX2KoJb5D9sfJruuqsqsrqBZTBBznYMRfk7RBo8EcKDodYJm529ykTr2wrK1KBKXCbdSPu74pA37hZmPxkCP3hbEJBuqJgruy
  * ext priv: xprv9xfLHXpU7kFDoqiqV3g9WXN8Mt1PSR8ypLXaPcNvo68mEcreahJ4g1K4TWqn4qu6HCKByGeivW9neAEzSS7idYdpGaGXJgvb79fxvV4qhse

I got the same result on [bip32.org](http://bip32.org/).

![image](https://user-images.githubusercontent.com/39208031/89793100-07a3c600-db58-11ea-8afa-bb61ee4f27c6.png)

As the result shows, this implementation might calculate a child key different from the one specified in BIP32 in some scenarios. As for the official BIP-0032 test vectors, the length of the serialization of their private key are all 32.

**Comment by bibibong** [comment]
@silencer-Tsai good case👍

**Comment by yl** [comment]
#161

**Comment by devrandom** [comment]
@ksedgwic just ran into this issue, and I noticed that there is this already open issue.  I submitted a PR just now, linked above.

**Comment by silencer-Tsai** [comment]
> @ksedgwic just ran into this issue, and I noticed that there is this already open issue. I submitted a PR just now, linked above.

I try to replace the original code with the following code. Hope to help.
https://github.com/btcsuite/btcutil/blob/4649e4b73b34090724fff8a302751260c20551fd/hdkeychain/extendedkey.go#L257
```go
copy(data[keyLen-len(k.key):], k.key)
```

**Comment by klim0v** [comment]
https://github.com/bitcoin/bips/pull/905

**Comment by afk11** [comment]
@silencer-Tsai if you haven't already, please submit it to BIP32 with the correct result? People randomly implementing and copy/pasting fixtures might run into it then. Plus a note to explain what to look for if it fails? :)

Always thought it'd be cool to write a standard testing interface for bitcoin libraries (all of them ideally) then vectors get added to the suite. This kind of bug (non-portable results due to implementation quirks) sucks and can be hard to detect for a long time if you always use the same software.. I can imagine a lot of stress trying to find out why electrum shows an empty balance but the servers say otherwise!

**Comment by benma** [comment]
Is this issue resolved?

**Comment by silencer-Tsai** [comment]
> Is this issue resolved?

@benma Yes. See https://github.com/btcsuite/btcutil/pull/182

**Comment by Roasbeef** [comment]
This has been resolved.

**Comment by Sintayew4** [comment]
#172
